const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const script=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8').match(/<script>([\s\S]*?)<\/script>/)[1];
function app(fetch=async()=>({ok:true,json:async()=>({found:0,hits:[]})})){
 const nodes=new Map();let focused=null;
 const get=id=>{if(!nodes.has(id)){const classes=new Set(id==='home'?['on']:[]);nodes.set(id,{value:'',textContent:'',innerHTML:'',scrollLeft:0,style:{},dataset:{},addEventListener(){},focus(){focused=id},classList:{add:c=>classes.add(c),remove:c=>classes.delete(c),contains:c=>classes.has(c)}})}return nodes.get(id)};
 const q=[get('query1'),get('query2')],picks=['cheapest','best','fastest'].map(p=>Object.assign(get(p),{dataset:{p}}));
 const document={getElementById:get,querySelectorAll:selector=>selector==='.qtxt'?q:selector==='[data-p]'?picks:selector==='.screen'?['home','choose','results'].map(get):[]};
 const context=vm.createContext({document,window:{scrollTo(){}},URL,URLSearchParams,Intl,AbortController,setTimeout,clearTimeout,console:{error(){}},fetch});vm.runInContext(script,context);
 return {get,run:code=>vm.runInContext(code,context),focused:()=>focused,search:()=>get('searchNow').onclick()};
}
test('wizard back preserves query and chosen preference, returns focus home',()=>{const a=app();a.run('start("iPhone");state.poison="cheapest"');a.get('wizardBack').onclick();assert.equal(a.get('heroInput').value,'iPhone');assert.equal(a.run('state.poison'),'cheapest');assert(a.get('home').classList.contains('on'));assert.equal(a.focused(),'heroInput');});
test('category search synchronizes native input for return navigation',()=>{const a=app();a.get('autoHot').onclick();a.get('wizardBack').onclick();assert.equal(a.get('heroInput').value,'automotive');});
test('wizard clear resets query, selection, result content and focus',()=>{const a=app();a.run('start("Nintendo");state.poison="fastest";products=[{title:"Consola"}]');a.get('list').innerHTML='old results';a.get('fastest').style.filter='brightness(1.2)';a.get('wizardClear').onclick();assert.equal(a.get('heroInput').value,'');assert.equal(a.run('state.q'),'');assert.equal(a.run('state.poison'),'best');assert.equal(a.get('query1').textContent,'');assert.equal(a.get('list').innerHTML,'');assert.equal(a.get('fastest').style.filter,'');assert.equal(a.run('products.length'),0);assert.equal(a.focused(),'heroInput');});
test('long and markup-like query stays literal and complete',()=>{const a=app();const q='<img onerror=alert(1)> '+'verylongquery'.repeat(100);a.context=undefined;a.run('start('+JSON.stringify(q)+')');assert.equal(a.get('query1').textContent,q);a.get('wizardBack').onclick();assert.equal(a.get('heroInput').value,q);});
test('clear aborts an in-flight request and ignores late results',async()=>{let finish,signal;const a=app((url,options)=>{signal=options.signal;return new Promise(resolve=>{finish=resolve})});a.run('start("iPhone")');const pending=a.search();a.run('clearSearch()');assert(signal.aborted);finish({ok:true,json:async()=>({found:1,hits:[{document:{title:'iPhone 16',price:3000}}]})});await pending;assert.equal(a.get('list').innerHTML,'');assert(a.get('home').classList.contains('on'));assert.equal(a.get('heroInput').value,'');});
